"""Models

Revision ID: 522a95b4cbb4
Revises: b57fef00b65d
Create Date: 2023-06-22 15:37:36.825922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "522a95b4cbb4"
down_revision = "b57fef00b65d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proposal_field")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposal_field",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("texto", "número", name="choices"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("nullable", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "order",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name="proposal_field_pkey"),
    )
    # ### end Alembic commands ###
