"""test 2

Revision ID: b72e3e2dc96c
Revises: 522a95b4cbb4
Create Date: 2023-06-22 16:15:34.968320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b72e3e2dc96c"
down_revision = "522a95b4cbb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("aprovado", "negado", "pendente", name="status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proposal_field",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("nullable", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "response",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["field_name"],
            ["proposal_field.name"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("response")
    op.drop_table("proposal_field")
    op.drop_table("proposal")
    # ### end Alembic commands ###
